### ISSUE TITLE
Invalid json when newline is at the beginning of a chunk

### ISSUE THREAD

**Issue by kokje** [mpetazzoni/sseclient#11]
Hi, If the response chunk happens to have a newline character at the beginning then it is incorrectly parsed as an SSE delimiter resulting in invalid json in event.data
ex: 

```
chunk = b'\ndata:   "logicalTimestampMs" : 1497016850000,\ndata:   "maxDelayMs" : 12000\ndata: }\n\nevent: data\nid: data-1497016860000\ndata: {\n'
chunk.splitlines(True)
['\n', 'data:   "logicalTimestampMs" : 1497016850000,\n', 'data:   "maxDelayMs" : 12000\n', 'data: }\n', '\n', 'event: data\n', 'id: data-1497016860000\n', 'data: {\n']
```

**Comment by mpetazzoni** [comment]
Do you have a more complete data stream? I'm having a hard time wrapping my head around the data that was received and how it was chunked

**Comment by davedoesdev** [comment]
The check [here](https://github.com/mpetazzoni/sseclient/blob/master/sseclient/__init__.py#L67) should pick up empty data.
@kokje Are you getting an exception?

**Comment by davedoesdev** [comment]
I'm getting this is a SignalFlow feed? https://developers.signalfx.com/v2/reference#signalflow-execute
