### ISSUE TITLE
Events arriving with one event delay on the client

### ISSUE THREAD

**Issue by rgabo74** [mpetazzoni/sseclient#6]
I recently deployed Openhab2, which is built is Eclipse Smarhome framework and it's REST API, including a SSE service. I can receive events with sseclient 1.4, but I observed I receive every event at the time when the next event is pushed by the server. So when the first event should come, nothing happens and after that all event arriving with one event delay. I checked if the server is sending the empty line delimiter and it does. 
Attaced is a screen capture with one event. Any suggestions welcome... 

Thanks, Gabor

![image](https://cloud.githubusercontent.com/assets/11273702/22827413/153dd288-ef98-11e6-897b-a0c265de11e3.png)

**Comment by mpetazzoni** [comment]
Could be a bug in the event stream parsing logic. I'll take a look!

**Comment by rgabo74** [comment]
I did some debuging. I found the empty line delimiter not arriving from the event source. As a workaround I am inserting an extra empty line when the chunk start with the data. This is dirty, I hope you can find the source of the issue.

        for chunk in self._event_source:
+            if(chunk[0:5]=="data:"):
+                 chunk += '\n'
            for line in chunk.splitlines(True):
                if not line.strip():
                    yield data
                    data = ''
                data += line.decode(self._char_enc)

**Comment by mpetazzoni** [comment]
If your event source doesn't send an empty line to delimit events then it's not complying to the spec. Is that what's going on, or do you mean that the library here is not seeing the empty line even though it's being sent?

**Comment by rgabo74** [comment]
I believe the server is sending the line delimiter after the message. (Please have a look at the screenshot, if you agree) For some reason the new line chunk does not arrive to the read method in the library, so the yield condition not satisfied.  When the next event pushed by the server later, that is when the previous event's delimited arrives. This is my theory...

**Comment by mpetazzoni** [comment]
Looking more into your problem, I found and fixed two bugs in sseclient-py, and just published an updated version 1.5. I believe one of those bugfixes will solve your issue. Can you try out the latest release and let me know if it works for you now?

**Comment by rgabo74** [comment]
I tested v1.5, but I still have the problem. I did a packet capture and found the problem to be on the server side. The empty line separator is sent before the event, not after. So I think you can keep this issue closed, I am seeking the resolution on the server side... Thanks! 

![image](https://cloud.githubusercontent.com/assets/11273702/22905727/a664c388-f241-11e6-98eb-876d03abc76c.png)

**Comment by mpetazzoni** [comment]
Thanks. It still made me find two bugs in the library, so it's a good thing I looked into it more!
