### ISSUE TITLE
Access without iteration

### ISSUE THREAD

**Issue by tomkcook** [mpetazzoni/sseclient#7]
I'm trying to use sseclient to get events which are then used in a Gtk application.  Obviously I can't just sit in an event-handling loop for the `SSEClient` object.  Is there a way to check whether new events are available and get them if they are?  Preferrably one that doesn't throw an exception when it reaches the end (for now) of the stream).

**Comment by mpetazzoni** [comment]
The `events()` method returns a Python generator, so the short answer is "no". You'd need a separate thread that consumes from the SSE event stream in a blocking way, and either emits the events via a callback, or puts them into a queue:

```python
import threading
import sseclient

def consume(url, callback):
    for e in sseclient.SSEClient(url).events():
        callback(e)

# callback can be whatever, or it can be something that puts into a shared queue:
def callback(e):
    q.offer(e)

t = threading.Thread(target=consume, args=(url, callback))
t.start()
```

**Comment by tomkcook** [comment]
Thanks, thought it looked that way.
